# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreDataHotelService' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoreDataHotelService
pod 'Flurry-iOS-SDK/FlurrySDK'
pod 'Flurry-iOS-SDK/FlurryAds'

  target 'CoreDataHotelServiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoreDataHotelServiceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
